Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.6
Creation-Date: 2024-11-07T04:37:48+02:00

====== LibrePhotos ======

	*todo !!! Удалить файл про LibrePhotos

Создайте файл Compose через URL:

	В OpenMediaVault перейдите в Compose > Files > Create from URL.
	В поле URL укажите репозиторий, содержащий конфигурацию Docker Compose для LibrePhotos. Официальная конфигурация находится по ссылке:

	https://raw.githubusercontent.com/LibrePhotos/librephotos/main/docker/docker-compose.yml

Настройте параметры:

	После загрузки файла убедитесь, что все пути и переменные окружения настроены для вашей системы. Параметры для баз данных, сети и пути к папке с фото можно изменить в этом файле.

Для настройки контейнера LibrePhotos на OpenMediaVault, используя параметры, подобные вашему примеру, создайте следующий Docker Compose файл. Он включает основные переменные окружения, указанные вами порты, а также директории для конфигурации и хранения данных.

'''
version: "3.8"

services:
  librephotos:
	image: reallibrephotos/librephotos
	container_name: librephotos
	environment:
	  - PUID=1002
	  - PGID=100
	  - TZ=Europe/Chisinau
	  - WEBUI_PORT=3000
	  - REDIS_HOST=redis
	  - DB_HOST=db
	  - DB_USER=astenix
	  - DB_PASS=562955
	  - DB_NAME=librephotos
	volumes:
	  - /srv/dev-disk-by-uuid-9b3771d9-c454-4acd-b683-568da8815820/docker/composefiles/LibrePhotos:/config
	  - /srv/dev-disk-by-uuid-9b3771d9-c454-4acd-b683-568da8815820/images/monitor_check_colors:/gallery
	ports:
	  - 8180:3000
	depends_on:
	  - db
	  - redis

  db:
	image: postgres:12
	container_name: librephotos-db
	environment:
	  - POSTGRES_USER=astenix
	  - POSTGRES_PASSWORD=562955
	  - POSTGRES_DB=librephotos
	volumes:
	  - /srv/dev-disk-by-uuid-9b3771d9-c454-4acd-b683-568da8815820/docker/data/LibrePhotos/db:/var/lib/postgresql/data

  redis:
	image: redis:alpine
	container_name: librephotos-redis
	volumes:
	  - /srv/dev-disk-by-uuid-9b3771d9-c454-4acd-b683-568da8815820/docker/data/LibrePhotos/redis:/data
'''


Порт веб-интерфейса (WEBUI_PORT): Переменная WEBUI_PORT=3000 в разделе environment и 8180:3000 в ports совпадают. Это правильно, так как 3000 — внутренний порт, а 8180 — внешний, который будет доступен через OMV.

Пояснение параметров

	environment — переменные окружения для настройки пользовательского ID (PUID) и группы (PGID), часового пояса и порта веб-интерфейса. Также указаны параметры для подключения к базе данных и Redis.
	volumes — примонтированные каталоги для конфигурации и хранения данных.
	ports — перенаправление порта 8181, чтобы сделать веб-интерфейс доступным.
	depends_on — указывает на необходимость запустить сначала db и redis, чтобы LibrePhotos корректно подключился к своим сервисам.

После настройки сохраните файл и запустите контейнеры, как обычно через OMV интерфейс, выбрав Compose > Files и команду Up.

После завершения установки вы сможете получить доступ к интерфейсу LibrePhotos по IP-адресу сервера OMV на порту, указанном в конфигурации (:3000 по умолчанию).

===== Ошибки =====

''sudo docker ps''

''CONTAINER ID   IMAGE          COMMAND                  CREATED              STATUS              PORTS      NAMES''
''8e42a1ab0db4   postgres:12    "docker-entrypoint.s…"   About a minute ago   Up About a minute   5432/tcp   librephotos-db''
''b88abf6a6af3   redis:alpine   "docker-entrypoint.s…"   About a minute ago   Up About a minute   6379/tcp   librephotos-redis''

Похоже, что контейнер librephotos не запущен, так как его нет в списке активных контейнеров. Это может быть связано с ошибкой в настройках Docker Compose файла или в конфигурации самого контейнера. В

time="2024-11-07T05:00:57+02:00" level=warning msg="/srv/dev-disk-by-uuid-9b3771d9-c454-4acd-b683-568da8815820/docker/composefiles/LibrePhotos/LibrePhotos.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
librephotos  | generate SECRET_KEY and save to file
librephotos  | use SECRET_KEY from file
librephotos  | Traceback (most recent call last):
librephotos  |   File "/code/manage.py", line 31, in <module>
librephotos        |     execute_from_command_line(sys.argv)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
librephotos        |     utility.execute()
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 382, in execute
librephotos        |     settings.INSTALLED_APPS
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 102, in __getattr__
librephotos        |     self._setup(name)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 89, in _setup
librephotos        |     self._wrapped = Settings(settings_module)
librephotos        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 217, in __init__
librephotos        |     mod = importlib.import_module(self.SETTINGS_MODULE)
librephotos        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
librephotos        |     return _bootstrap._gcd_import(name[level:], package, level)
librephotos        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
librephotos        |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
librephotos        |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
librephotos        |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
librephotos        |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
librephotos        |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
librephotos        |   File "/code/librephotos/settings/production.py", line 80, in <module>
librephotos        |     int(HEAVYWEIGHT_PROCESS_ENV) if HEAVYWEIGHT_PROCESS_ENV.isnumeric() else None
librephotos        |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        | AttributeError: 'NoneType' object has no attribute 'isnumeric'
librephotos        | use SECRET_KEY from file
librephotos        | Traceback (most recent call last):
librephotos        |   File "/code/manage.py", line 31, in <module>
librephotos        |     execute_from_command_line(sys.argv)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
librephotos        |     utility.execute()
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 382, in execute
librephotos        |     settings.INSTALLED_APPS
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 102, in __getattr__
librephotos        |     self._setup(name)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 89, in _setup
librephotos        |     self._wrapped = Settings(settings_module)
librephotos        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 217, in __init__
librephotos        |     mod = importlib.import_module(self.SETTINGS_MODULE)
librephotos        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
librephotos        |     return _bootstrap._gcd_import(name[level:], package, level)
librephotos        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
librephotos        |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
librephotos        |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
librephotos        |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
librephotos        |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
librephotos        |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
librephotos        |   File "/code/librephotos/settings/production.py", line 80, in <module>
librephotos        |     int(HEAVYWEIGHT_PROCESS_ENV) if HEAVYWEIGHT_PROCESS_ENV.isnumeric() else None
librephotos        |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        | AttributeError: 'NoneType' object has no attribute 'isnumeric'
librephotos        | use SECRET_KEY from file
librephotos        | Traceback (most recent call last):
librephotos        |   File "/code/manage.py", line 31, in <module>
librephotos        |     execute_from_command_line(sys.argv)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
librephotos        |     utility.execute()
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 382, in execute
librephotos        |     settings.INSTALLED_APPS
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 102, in __getattr__
librephotos        |     self._setup(name)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 89, in _setup
librephotos        |     self._wrapped = Settings(settings_module)
librephotos        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 217, in __init__
librephotos        |     mod = importlib.import_module(self.SETTINGS_MODULE)
librephotos        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
librephotos        |     return _bootstrap._gcd_import(name[level:], package, level)
librephotos        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
librephotos        |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
librephotos        |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
librephotos        |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
librephotos        |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
librephotos        |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
librephotos        |   File "/code/librephotos/settings/production.py", line 80, in <module>
librephotos        |     int(HEAVYWEIGHT_PROCESS_ENV) if HEAVYWEIGHT_PROCESS_ENV.isnumeric() else None
librephotos        |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        | AttributeError: 'NoneType' object has no attribute 'isnumeric'
librephotos        | use SECRET_KEY from file
librephotos        | Traceback (most recent call last):
librephotos        |   File "/code/manage.py", line 31, in <module>
librephotos        |     execute_from_command_line(sys.argv)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
librephotos        |     utility.execute()
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 382, in execute
librephotos        |     settings.INSTALLED_APPS
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 102, in __getattr__
librephotos        |     self._setup(name)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 89, in _setup
librephotos        |     self._wrapped = Settings(settings_module)
librephotos        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 217, in __init__
librephotos        |     mod = importlib.import_module(self.SETTINGS_MODULE)
librephotos        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
librephotos        |     return _bootstrap._gcd_import(name[level:], package, level)
librephotos        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
librephotos        |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
librephotos        |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
librephotos-db     | 
librephotos-db     | PostgreSQL Database directory appears to contain a database; Skipping initialization
librephotos-db     | 
librephotos-db     | 2024-11-07 02:57:57.862 UTC [1] LOG:  starting PostgreSQL 12.20 (Debian 12.20-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
librephotos-db     | 2024-11-07 02:57:57.863 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
librephotos        |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
librephotos        |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
librephotos        |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
librephotos        |   File "/code/librephotos/settings/production.py", line 80, in <module>
librephotos        |     int(HEAVYWEIGHT_PROCESS_ENV) if HEAVYWEIGHT_PROCESS_ENV.isnumeric() else None
librephotos        |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        | AttributeError: 'NoneType' object has no attribute 'isnumeric'
librephotos        | use SECRET_KEY from file
librephotos        | Traceback (most recent call last):
librephotos        |   File "/code/manage.py", line 31, in <module>
librephotos        |     execute_from_command_line(sys.argv)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
librephotos        |     utility.execute()
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 382, in execute
librephotos        |     settings.INSTALLED_APPS
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 102, in __getattr__
librephotos        |     self._setup(name)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 89, in _setup
librephotos        |     self._wrapped = Settings(settings_module)
librephotos        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 217, in __init__
librephotos        |     mod = importlib.import_module(self.SETTINGS_MODULE)
librephotos        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
librephotos        |     return _bootstrap._gcd_import(name[level:], package, level)
librephotos        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
librephotos        |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
librephotos        |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
librephotos        |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
librephotos        |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
librephotos        |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
librephotos        |   File "/code/librephotos/settings/production.py", line 80, in <module>
librephotos        |     int(HEAVYWEIGHT_PROCESS_ENV) if HEAVYWEIGHT_PROCESS_ENV.isnumeric() else None
librephotos        |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        | AttributeError: 'NoneType' object has no attribute 'isnumeric'
librephotos        | use SECRET_KEY from file
librephotos        | Traceback (most recent call last):
librephotos        |   File "/code/manage.py", line 31, in <module>
librephotos        |     execute_from_command_line(sys.argv)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
librephotos        |     utility.execute()
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 382, in execute
librephotos        |     settings.INSTALLED_APPS
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 102, in __getattr__
librephotos        |     self._setup(name)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 89, in _setup
librephotos        |     self._wrapped = Settings(settings_module)
librephotos        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 217, in __init__
librephotos        |     mod = importlib.import_module(self.SETTINGS_MODULE)
librephotos        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
librephotos        |     return _bootstrap._gcd_import(name[level:], package, level)
librephotos        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
librephotos        |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
librephotos        |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
librephotos        |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
librephotos        |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
librephotos        |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
librephotos        |   File "/code/librephotos/settings/production.py", line 80, in <module>
librephotos        |     int(HEAVYWEIGHT_PROCESS_ENV) if HEAVYWEIGHT_PROCESS_ENV.isnumeric() else None
librephotos        |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        | AttributeError: 'NoneType' object has no attribute 'isnumeric'
librephotos        | use SECRET_KEY from file
librephotos        | Traceback (most recent call last):
librephotos        |   File "/code/manage.py", line 31, in <module>
librephotos        |     execute_from_command_line(sys.argv)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
librephotos        |     utility.execute()
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 382, in execute
librephotos        |     settings.INSTALLED_APPS
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 102, in __getattr__
librephotos        |     self._setup(name)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 89, in _setup
librephotos        |     self._wrapped = Settings(settings_module)
librephotos-db     | 2024-11-07 02:57:57.863 UTC [1] LOG:  listening on IPv6 address "::", port 5432
librephotos-db     | 2024-11-07 02:57:58.017 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
librephotos-db     | 2024-11-07 02:57:58.254 UTC [27] LOG:  database system was shut down at 2024-11-07 02:54:19 UTC
librephotos-db     | 2024-11-07 02:57:58.384 UTC [1] LOG:  database system is ready to accept connections
librephotos-redis  | 1:C 07 Nov 2024 02:57:57.059 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
librephotos-redis  | 1:C 07 Nov 2024 02:57:57.060 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
librephotos-redis  | 1:C 07 Nov 2024 02:57:57.060 * Redis version=7.4.1, bits=64, commit=00000000, modified=0, pid=1, just started
librephotos-redis  | 1:C 07 Nov 2024 02:57:57.060 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
librephotos-redis  | 1:M 07 Nov 2024 02:57:57.062 * monotonic clock: POSIX clock_gettime
librephotos-redis  | 1:M 07 Nov 2024 02:57:57.076 * Running mode=standalone, port=6379.
librephotos-redis  | 1:M 07 Nov 2024 02:57:57.077 * Server initialized
librephotos-redis  | 1:M 07 Nov 2024 02:57:57.101 * Loading RDB produced by version 7.4.1
librephotos-redis  | 1:M 07 Nov 2024 02:57:57.101 * RDB age 223 seconds
librephotos-redis  | 1:M 07 Nov 2024 02:57:57.101 * RDB memory usage when created 0.90 Mb
librephotos-redis  | 1:M 07 Nov 2024 02:57:57.101 * Done loading RDB, keys loaded: 0, keys expired: 0.
librephotos-redis  | 1:M 07 Nov 2024 02:57:57.101 * DB loaded from disk: 0.024 seconds
librephotos-redis  | 1:M 07 Nov 2024 02:57:57.102 * Ready to accept connections tcp
librephotos        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 217, in __init__
librephotos        |     mod = importlib.import_module(self.SETTINGS_MODULE)
librephotos        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
librephotos        |     return _bootstrap._gcd_import(name[level:], package, level)
librephotos        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
librephotos        |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
librephotos        |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
librephotos        |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
librephotos        |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
librephotos        |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
librephotos        |   File "/code/librephotos/settings/production.py", line 80, in <module>
librephotos        |     int(HEAVYWEIGHT_PROCESS_ENV) if HEAVYWEIGHT_PROCESS_ENV.isnumeric() else None
librephotos        |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        | AttributeError: 'NoneType' object has no attribute 'isnumeric'
librephotos        | use SECRET_KEY from file
librephotos        | Traceback (most recent call last):
librephotos        |   File "/code/manage.py", line 31, in <module>
librephotos        |     execute_from_command_line(sys.argv)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
librephotos        |     utility.execute()
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 382, in execute
librephotos        |     settings.INSTALLED_APPS
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 102, in __getattr__
librephotos        |     self._setup(name)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 89, in _setup
librephotos        |     self._wrapped = Settings(settings_module)
librephotos        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 217, in __init__
librephotos        |     mod = importlib.import_module(self.SETTINGS_MODULE)
librephotos        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
librephotos        |     return _bootstrap._gcd_import(name[level:], package, level)
librephotos        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
librephotos        |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
librephotos        |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
librephotos        |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
librephotos        |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
librephotos        |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
librephotos        |   File "/code/librephotos/settings/production.py", line 80, in <module>
librephotos        |     int(HEAVYWEIGHT_PROCESS_ENV) if HEAVYWEIGHT_PROCESS_ENV.isnumeric() else None
librephotos        |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        | AttributeError: 'NoneType' object has no attribute 'isnumeric'
librephotos        | Running backend server...
librephotos        | production backend starting
librephotos        | use SECRET_KEY from file
librephotos        | Traceback (most recent call last):
librephotos        |   File "/code/manage.py", line 31, in <module>
librephotos        |     execute_from_command_line(sys.argv)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
librephotos        |     utility.execute()
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/management/__init__.py", line 382, in execute
librephotos        |     settings.INSTALLED_APPS
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 102, in __getattr__
librephotos        |     self._setup(name)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 89, in _setup
librephotos        |     self._wrapped = Settings(settings_module)
librephotos        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 217, in __init__
librephotos        |     mod = importlib.import_module(self.SETTINGS_MODULE)
librephotos        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
librephotos        |     return _bootstrap._gcd_import(name[level:], package, level)
librephotos        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
librephotos        |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
librephotos        |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
librephotos        |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
librephotos        |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
librephotos        |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
librephotos        |   File "/code/librephotos/settings/production.py", line 80, in <module>
librephotos        |     int(HEAVYWEIGHT_PROCESS_ENV) if HEAVYWEIGHT_PROCESS_ENV.isnumeric() else None
librephotos        |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        | AttributeError: 'NoneType' object has no attribute 'isnumeric'
librephotos        | [2024-11-07 04:58:03 +0200] [23] [INFO] Starting gunicorn 23.0.0
librephotos        | [2024-11-07 04:58:03 +0200] [23] [INFO] Listening at: http://0.0.0.0:8001 (23)
librephotos        | [2024-11-07 04:58:03 +0200] [23] [INFO] Using worker: gevent
librephotos        | [2024-11-07 04:58:03 +0200] [25] [INFO] Booting worker with pid: 25
librephotos        | use SECRET_KEY from file
librephotos        | [2024-11-07 04:58:05 +0200] [25] [ERROR] Exception in worker process
librephotos        | Traceback (most recent call last):
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/gunicorn/arbiter.py", line 608, in spawn_worker
librephotos        |     worker.init_process()
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/gunicorn/workers/ggevent.py", line 146, in init_process
librephotos        |     super().init_process()
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/gunicorn/workers/base.py", line 135, in init_process
librephotos        |     self.load_wsgi()
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/gunicorn/workers/base.py", line 147, in load_wsgi
librephotos        |     self.wsgi = self.app.wsgi()
librephotos        |                 ^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/gunicorn/app/base.py", line 66, in wsgi
librephotos        |     self.callable = self.load()
librephotos        |                     ^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/gunicorn/app/wsgiapp.py", line 57, in load
librephotos        |     return self.load_wsgiapp()
librephotos        |            ^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
librephotos        |     return util.import_app(self.app_uri)
librephotos        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/gunicorn/util.py", line 370, in import_app
librephotos        |     mod = importlib.import_module(module)
librephotos        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
librephotos        |     return _bootstrap._gcd_import(name[level:], package, level)
librephotos        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
librephotos        |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
librephotos        |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
librephotos        |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
librephotos        |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
librephotos        |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
librephotos        |   File "/code/librephotos/wsgi.py", line 11, in <module>
librephotos        |     application = get_wsgi_application()
librephotos        |                   ^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
librephotos        |     django.setup(set_prefix=False)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/__init__.py", line 19, in setup
librephotos        |     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
librephotos        |                       ^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 102, in __getattr__
librephotos        |     self._setup(name)
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 89, in _setup
librephotos        |     self._wrapped = Settings(settings_module)
librephotos        |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/local/lib/python3.12/dist-packages/django/conf/__init__.py", line 217, in __init__
librephotos        |     mod = importlib.import_module(self.SETTINGS_MODULE)
librephotos        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
librephotos        |     return _bootstrap._gcd_import(name[level:], package, level)
librephotos        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
librephotos        |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
librephotos        |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
librephotos        |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
librephotos        |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
librephotos        |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
librephotos        |   File "/code/librephotos/settings/production.py", line 80, in <module>
librephotos        |     int(HEAVYWEIGHT_PROCESS_ENV) if HEAVYWEIGHT_PROCESS_ENV.isnumeric() else None
librephotos        |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
librephotos        | AttributeError: 'NoneType' object has no attribute 'isnumeric'
librephotos        | [2024-11-07 04:58:05 +0200] [25] [INFO] Worker exiting (pid: 25)
librephotos        | [2024-11-07 04:58:05 +0200] [23] [ERROR] Worker (pid:25) exited with code 3
librephotos        | [2024-11-07 04:58:05 +0200] [23] [ERROR] Shutting down: Master
librephotos        | [2024-11-07 04:58:05 +0200] [23] [ERROR] Reason: Worker failed to boot.

END OF LINE
